### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by SeongMyeong** [SeongMyeong/umamusume_banpick#1]
function list

- [x] JSON 파일 읽어서 화면에 말딸 그리기
- [x] 특정 말딸 선택 시 Ban / Pick 이벤트 적용하기 (CSS로 회색으로 변경?)
- [ ] Ban / Pick 이후 input 박스를 통한 검색 -> 초기화 시 기존 Ban / Pick 유지
- [x] 한글/영문 으로 말딸 검색 (검색시 해당 말딸만 화면에 노출하는 식으로)
- [ ] 1경기 시작 시 일정 풀 내에서 랜덤하게 1마리 밴 선택
  - [ ] 일부/전체 중 하나 선택
    - [ ] 일부 선택 시 랜덤 밴 가능한 말딸 목록 기입 가능(선택/입력 등등)
    - [ ] 전체 선택 시 현재 모든 말딸 중 랜덤으로 돌아감
  - [ ] 시작-종료 버튼으로 밴 선택 가능
- [ ] N 번째 경기부터는 N-1 번째 경기의 패자가 밴을 선택하므로 따로 랜덤으로 돌릴필요 X

**Comment by SeongMyeong** [comment]
필요기능 도입시마다 Issue 로 추가하기
